fix: enhance Checkov workflow to add findings as PR comment and improve output formatting

diff --git a/.github/workflows/detect_breaking_changes.yaml b/.github/workflows/detect_breaking_changes.yaml
--- a/.github/workflows/detect_breaking_changes.yaml
+++ b/.github/workflows/detect_breaking_changes.yaml
@@ -8,7 +8,13 @@ jobs:
   openapi-diff:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth:
+
+      - name: Fetch main branch
+        run: git fetch origin main
 
       - name: Get changed files
         uses: dorny/paths-filter@v3
@@ -19,13 +25,14 @@ jobs:
             openapi:
               - 'environments/prod/apis/**' 
               - 'environments/staging/apis/**'
-      
+
       - run: |
           for file in ${{ steps.changed_files.outputs.openapi_files }}; do
             if [[ $file == *.json ]]; then
+              echo "CHANGED FILE VERSION:"
               cat $file
-              echo "\n\nORIGINAL VERSION:"
-              git -c "http.extraHeader=Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" show origin/main:$file
+              echo "\n\nORIGINAL VERSION FROM MAIN:"
+              git show origin/main:"$file" || echo "File $file not found in main"
             fi
           done
         shell: bash
